Modo depuración: Activado
======================
 * Serving Flask app 'app'
 * Debug mode: on
2025-04-05 12:36:02,149 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
2025-04-05 12:36:02,149 - werkzeug - INFO - Press CTRL+C to quit
2025-04-05 12:36:02,150 - werkzeug - INFO -  * Restarting with watchdog (windowsapi)
=== Iniciando Áureo ===
Host: 127.0.0.1
Puerto: 5000
Modo depuración: Activado
======================
2025-04-05 12:36:02,965 - werkzeug - WARNING -  * Debugger is active!
2025-04-05 12:36:02,967 - werkzeug - INFO -  * Debugger PIN: 267-544-666
2025-04-05 12:36:08,191 - aureo - INFO - Vigilancia de archivos deshabilitada por configuración
2025-04-05 12:36:08,191 - aureo - INFO - Componentes inicializados correctamente
2025-04-05 12:36:08,193 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:08] "GET / HTTP/1.1" 200 -
2025-04-05 12:36:08,407 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:08] "GET /favicon.ico HTTP/1.1" 200 -
2025-04-05 12:36:09,898 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:09] "GET /auth HTTP/1.1" 200 -
2025-04-05 12:36:10,012 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:10] "GET /favicon.ico HTTP/1.1" 200 -
2025-04-05 12:36:13,925 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:13] "POST /api/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 183, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 941, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_session\sessions.py", line 362, in save_session
    response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\sansio\response.py", line 232, in set_cookie
    dump_cookie(
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\http.py", line 1335, in dump_cookie
    if not _cookie_no_quote_re.fullmatch(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
2025-04-05 12:36:17,939 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:17] "POST /api/login HTTP/1.1" 401 -
2025-04-05 12:36:22,078 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:22] "POST /api/login HTTP/1.1" 401 -
2025-04-05 12:36:27,038 - werkzeug - INFO - 127.0.0.1 - - [05/Apr/2025 12:36:27] "POST /api/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\middleware\proxy_fix.py", line 183, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 941, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_session\sessions.py", line 362, in save_session
    response.set_cookie(app.config["SESSION_COOKIE_NAME"], session_id,
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\sansio\response.py", line 232, in set_cookie
    dump_cookie(
  File "C:\Users\s4lvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\http.py", line 1335, in dump_cookie
    if not _cookie_no_quote_re.fullmatch(value):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
